theme:          jekyll-theme-minimal
title:          home
description:    my good place

owner:
    name: Edu Nunes
    avatar: https://raw.githubusercontent.com/dioph/dioph.github.io/master/images/rocktor.gif
    bio: Undergrad EE & Physics
    email: diofanto.nunes@gmail.com
    github: dioph
    

